//! The hand-picked side of the daily posts. The topic lists are only Wikipedia
//! article titles - every fact in a post comes from the article, not from here.
//! The poems and quotes ARE the content, so each one is a well-known line with
//! an attribution that isn't disputed; a line whose author is argued over
//! (a lot of "Ghalib" and "Ali" on the internet) is deliberately left out.

/// Indian-subcontinent history: people, places, battles, discoveries.
pub const INDIA_HISTORY: &[&str] = &[
    "Koh-i-Noor", "Siege of Chittorgarh (1567–1568)", "Battle of Saragarhi", "Rani Lakshmibai", "Nalanda mahavihara",
    "Mohenjo-daro", "Great Bath, Mohenjo-daro", "Iron pillar of Delhi", "Taj Mahal", "Peacock Throne",
    "Nader Shah's invasion of the Mughal Empire", "Jallianwala Bagh massacre", "Salt March", "Chauri Chaura incident",
    "Kakori conspiracy", "Bhagat Singh", "Indian National Army", "Royal Indian Navy mutiny", "Partition of India",
    "Annexation of Hyderabad", "Annexation of Goa", "The Emergency (India)", "Pokhran-II", "Chola navy",
    "Rajendra I", "Ashoka", "Kalinga War", "Chandragupta Maurya", "Arthashastra", "Aryabhata", "Brahmagupta",
    "Vijayanagara Empire", "Hampi", "Battle of Talikota", "Krishnadevaraya", "Shivaji", "Battle of Pratapgarh",
    "Tanaji Malusare", "Third Battle of Panipat", "Battle of Plassey", "Tipu Sultan", "Tipu's Tiger",
    "Battle of Haldighati", "Maharana Pratap", "Prithviraj Chauhan", "Razia Sultan", "Alauddin Khalji",
    "Muhammad bin Tughluq", "Sher Shah Suri", "Grand Trunk Road", "Akbar", "Fatehpur Sikri", "Din-i Ilahi",
    "Dara Shikoh", "Jahanara Begum", "Nur Jahan", "Ahilyabai Holkar", "Velu Nachiyar", "Kittur Chennamma",
    "Ranjit Singh", "Hari Singh Nalwa", "Battle of Chamkaur", "Indian Rebellion of 1857", "Mangal Pandey",
    "Siege of Lucknow", "Bahadur Shah Zafar", "Begum Hazrat Mahal", "Sanchi", "Ajanta Caves", "Ellora Caves",
    "Kailasa temple, Ellora", "Konark Sun Temple", "Brihadisvara Temple, Thanjavur", "Khajuraho Group of Monuments",
    "Jantar Mantar, Jaipur", "Jai Singh II", "Qutb Minar", "Golconda Fort", "Charminar", "Kollur Mine",
    "Mir Osman Ali Khan", "Srinivasa Ramanujan", "Jagadish Chandra Bose", "C. V. Raman", "Homi J. Bhabha",
    "Vikram Sarabhai", "Aryabhata (satellite)", "Chandrayaan-3", "Mars Orbiter Mission", "1983 Cricket World Cup",
    "Dhyan Chand", "Milkha Singh", "Bhopal disaster", "Green Revolution in India", "Operation Flood",
    "Quit India Movement", "Swadeshi movement", "Partition of Bengal (1905)", "Komagata Maru incident",
    "Ghadar Mutiny", "Cellular Jail", "Black Hole of Calcutta", "Hyder Ali", "Zamorin", "Kunjali Marakkar",
    "Abbakka Chowta", "Lachit Borphukan", "Battle of Saraighat", "Ahom kingdom", "Kanishka", "Xuanzang", "Taxila",
    "Chanakya", "Samudragupta", "Kalidasa", "Gupta Empire", "Shore Temple", "Nek Chand", "Lothal", "Dholavira",
    "Rakhigarhi", "Roopkund Lake", "Bhangarh Fort", "Shaniwar Wada", "Mehrangarh", "Jaisalmer Fort", "Kumbhalgarh",
    "Humayun's Tomb", "Red Fort", "Tughlaqabad Fort", "Rani ki vav", "Siege of Delhi",
    "Battle of Buxar", "Maratha Navy", "Kanhoji Angre", "Battle of Colachel", "Marthanda Varma", "Battle of Longewala",
    "Operation Meghdoot", "Tashkent Declaration", "Simla Agreement", "Kargil War", "Indo-Pakistani war of 1971",
    "Battle of Kohima",
];

/// Musicians, bands, albums and songs, Western and South Asian.
pub const MUSIC: &[&str] = &[
    "Bohemian Rhapsody", "Queen (band)", "The Beatles", "Abbey Road", "Sgt. Pepper's Lonely Hearts Club Band",
    "Pink Floyd", "The Dark Side of the Moon", "The Wall (album)", "Led Zeppelin", "Stairway to Heaven",
    "Michael Jackson", "Thriller (album)", "Nirvana (band)", "Smells Like Teen Spirit", "Metallica", "AC/DC",
    "Back in Black", "Hotel California", "Fleetwood Mac", "Rumours (album)", "David Bowie", "Freddie Mercury",
    "Jimi Hendrix", "Woodstock", "Live Aid", "The Rolling Stones", "Bob Marley", "Radiohead", "OK Computer",
    "Daft Punk", "Linkin Park", "Hybrid Theory", "Coldplay", "Eminem", "Tupac Shakur", "Kendrick Lamar",
    "Taylor Swift", "Adele", "Billie Eilish", "Beyoncé", "Johnny Cash", "Elvis Presley", "Ray Charles",
    "Louis Armstrong", "Miles Davis", "Kind of Blue", "Ludwig van Beethoven", "Symphony No. 9 (Beethoven)",
    "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Pyotr Ilyich Tchaikovsky", "Imagine (John Lennon song)",
    "Like a Rolling Stone", "Bob Dylan", "Hallelujah (Leonard Cohen song)", "Gangnam Style", "BTS",
    "Despacito", "Hans Zimmer", "Ennio Morricone", "John Williams", "ABBA", "Pet Sounds", "Prince (musician)",
    "Purple Rain (album)", "Whitney Houston", "Guns N' Roses", "Iron Maiden", "Black Sabbath", "The Who",
    "A. R. Rahman", "Jai Ho (song)", "Lata Mangeshkar", "Asha Bhosle", "Kishore Kumar", "Mohammed Rafi",
    "R. D. Burman", "S. D. Burman", "Ilaiyaraaja", "Nusrat Fateh Ali Khan", "Mehdi Hassan", "Jagjit Singh",
    "Ghulam Ali (singer)", "Abida Parveen", "Noor Jehan", "Begum Akhtar", "Ravi Shankar", "Zakir Hussain (musician)",
    "Bismillah Khan", "M. S. Subbulakshmi", "Tansen", "Amir Khusrau", "Qawwali", "Indian Ocean (band)",
    "Junoon (band)", "Vital Signs (band)", "Coke Studio Pakistan", "Pasoori", "Arijit Singh", "Shankar–Ehsaan–Loy",
    "Lucky Ali", "Why This Kolaveri Di", "Sonu Nigam", "K. J. Yesudas", "S. P. Balasubrahmanyam", "Laxmikant–Pyarelal",
    "Ae Mere Watan Ke Logo", "Vande Mataram", "AP Dhillon", "Diljit Dosanjh", "Sidhu Moose Wala", "Prateek Kuhad",
    "Parikrama (band)", "Euphoria (Indian band)", "Shreya Ghoshal", "Kailash Kher", "Amit Trivedi", "Atif Aslam",
    "Ali Sethi", "Rahat Fateh Ali Khan", "Salil Chowdhury", "Madan Mohan (composer)", "Naushad", "Talat Mahmood",
    "Kumar Sanu", "Udit Narayan", "Alka Yagnik", "Hariprasad Chaurasia", "Bhimsen Joshi", "Kishori Amonkar",
];

/// Books and writers: world literature, Indian and Urdu literature.
pub const BOOKS: &[&str] = &[
    "Nineteen Eighty-Four", "Animal Farm", "Brave New World", "Fahrenheit 451", "To Kill a Mockingbird",
    "The Great Gatsby", "The Catcher in the Rye", "Lolita", "Ulysses (novel)", "Lady Chatterley's Lover",
    "The Satanic Verses", "Midnight's Children", "The God of Small Things", "A Suitable Boy",
    "The White Tiger (Adiga novel)", "Train to Pakistan", "Godaan", "Premchand", "Rabindranath Tagore",
    "Gitanjali", "Gora (novel)", "R. K. Narayan", "Malgudi Days (short story collection)", "Ruskin Bond", "Amrita Pritam", "Pinjar (novel)",
    "Saadat Hasan Manto", "Toba Tek Singh (short story)", "Ismat Chughtai", "Lihaaf", "Qurratulain Hyder",
    "Aag Ka Darya", "Umrao Jaan Ada", "Bano Qudsia", "Mushtaq Ahmad Yusufi", "Intizar Hussain",
    "The Guide", "Tamas (novel)", "Raag Darbari", "Devdas (novel)", "Chemmeen", "Harry Potter",
    "J. K. Rowling", "The Lord of the Rings", "J. R. R. Tolkien", "The Hobbit", "Frankenstein", "Dracula",
    "Mary Shelley", "Pride and Prejudice", "Jane Austen", "Wuthering Heights", "Moby-Dick", "War and Peace",
    "Crime and Punishment", "The Brothers Karamazov", "Anna Karenina", "Don Quixote",
    "One Hundred Years of Solitude", "The Little Prince", "The Alchemist (novel)", "The Kite Runner",
    "The Diary of a Young Girl", "The Book Thief", "Sherlock Holmes", "Arthur Conan Doyle", "Agatha Christie",
    "And Then There Were None", "The Da Vinci Code", "The Hitchhiker's Guide to the Galaxy", "Dune (novel)",
    "A Brief History of Time", "Sapiens: A Brief History of Humankind", "On the Origin of Species",
    "The Communist Manifesto", "The Prince", "The Art of War", "Meditations", "Rubaiyat of Omar Khayyam",
    "Masnavi", "Shahnameh", "One Thousand and One Nights", "Panchatantra", "Ramcharitmanas",
    "The Discovery of India", "Wings of Fire (autobiography)", "The Story of My Experiments with Truth",
    "Annihilation of Caste", "Things Fall Apart", "Beloved (novel)", "Invisible Man", "The Grapes of Wrath",
    "Catch-22", "Slaughterhouse-Five", "The Handmaid's Tale", "Little Women", "Alice's Adventures in Wonderland",
    "Gulliver's Travels", "Robinson Crusoe", "Treasure Island", "The Picture of Dorian Gray", "Oscar Wilde",
    "Franz Kafka", "The Metamorphosis", "The Trial", "Ernest Hemingway", "The Old Man and the Sea",
    "Charles Dickens", "A Christmas Carol", "Leo Tolstoy", "Fyodor Dostoevsky", "Virginia Woolf", "George Orwell",
    "Salman Rushdie", "Arundhati Roy", "Vikram Seth", "Khushwant Singh", "Mulk Raj Anand", "Munshi Premchand",
    "Mahasweta Devi", "Bankim Chandra Chatterjee", "Anandamath", "Sarat Chandra Chattopadhyay", "Chetan Bhagat",
];

/// Video games, old and landmark.
pub const GAMES: &[&str] = &[
    "Pac-Man", "Tetris", "Super Mario Bros.", "The Legend of Zelda (video game)", "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: Breath of the Wild", "Pokémon Red and Blue", "Street Fighter II", "Mortal Kombat (1992 video game)",
    "Doom (1993 video game)", "Quake (video game)", "Half-Life (video game)", "Half-Life 2", "Counter-Strike (video game)",
    "StarCraft (video game)", "Warcraft III: Reign of Chaos", "Defense of the Ancients", "Dota 2", "League of Legends",
    "World of Warcraft", "Diablo II", "Age of Empires II", "Road Rash", "Grand Theft Auto: Vice City",
    "Grand Theft Auto: San Andreas", "Grand Theft Auto V", "Red Dead Redemption 2", "Minecraft",
    "The Elder Scrolls V: Skyrim", "The Witcher 3: Wild Hunt", "Cyberpunk 2077", "Dark Souls (video game)", "Elden Ring",
    "Metal Gear Solid (1998 video game)", "Final Fantasy VII", "Resident Evil (1996 video game)", "Silent Hill (video game)",
    "Tomb Raider (1996 video game)", "Prince of Persia (1989 video game)", "Prince of Persia: The Sands of Time",
    "Assassin's Creed (video game)", "Assassin's Creed II", "Need for Speed: Most Wanted (2005 video game)",
    "Call of Duty 4: Modern Warfare", "Halo: Combat Evolved", "BioShock (video game)", "Portal (video game)", "Portal 2",
    "The Last of Us", "Uncharted 2: Among Thieves", "God of War (2018 video game)", "Shadow of the Colossus",
    "Journey (2012 video game)", "Undertale", "Hollow Knight", "Stardew Valley", "Among Us", "Fortnite",
    "PUBG: Battlegrounds", "Garena Free Fire", "Clash of Clans", "Angry Birds (video game)", "Candy Crush Saga",
    "Pokémon Go", "Flappy Bird", "Subway Surfers", "Temple Run", "Mario Kart 64", "GoldenEye 007 (1997 video game)",
    "Super Mario 64", "Sonic the Hedgehog (1991 video game)", "Contra (video game)", "Duck Hunt",
    "E.T. the Extra-Terrestrial (video game)", "Video game crash of 1983", "Space Invaders", "Pong",
    "SimCity (1989 video game)", "The Sims (video game)", "Civilization (video game)", "RollerCoaster Tycoon (video game)",
    "Mafia (video game)", "Max Payne (video game)", "Deus Ex (video game)", "Baldur's Gate 3", "Hades (video game)",
    "Raji: An Ancient Epic", "Ghost of Tsushima", "Marvel's Spider-Man (2018 video game)", "Batman: Arkham Asylum",
    "Mass Effect 2", "Fallout: New Vegas", "Red Dead Redemption", "Metroid (video game)", "Chrono Trigger",
    "Castlevania: Symphony of the Night", "Grand Theft Auto III", "Hitman: Blood Money", "Far Cry 3", "Terraria",
    "Celeste (video game)", "Cuphead", "Outer Wilds", "Disco Elysium", "It Takes Two (video game)",
];

/// A few lines of verse and who wrote them. Roman Urdu is written the way
/// people type it, not in a scholarly transliteration.
pub struct Poem {
    pub id: &'static str,
    pub poet: &'static str,
    pub lines: &'static [&'static str],
    /// "urdu" or "english".
    pub language: &'static str,
}

const fn urdu(id: &'static str, poet: &'static str, lines: &'static [&'static str]) -> Poem {
    Poem { id, poet, lines, language: "urdu" }
}

const fn english(id: &'static str, poet: &'static str, lines: &'static [&'static str]) -> Poem {
    Poem { id, poet, lines, language: "english" }
}

pub const POEMS: &[Poem] = &[
    urdu("ghalib-hazaron", "Mirza Ghalib", &["Hazaaron khwahishen aisi ke har khwahish pe dam nikle", "Bahut nikle mere armaan lekin phir bhi kam nikle"]),
    urdu("ghalib-dil-e-nadaan", "Mirza Ghalib", &["Dil-e-nadaan tujhe hua kya hai", "Aakhir is dard ki dawa kya hai"]),
    urdu("ghalib-nikamma", "Mirza Ghalib", &["Ishq ne Ghalib nikamma kar diya", "Varna hum bhi aadmi the kaam ke"]),
    urdu("ghalib-jannat", "Mirza Ghalib", &["Hum ko maloom hai jannat ki haqeeqat lekin", "Dil ke khush rakhne ko Ghalib ye khayal achha hai"]),
    urdu("ghalib-mir-bhi-tha", "Mirza Ghalib", &["Rekhte ke tumhi ustaad nahin ho Ghalib", "Kehte hain agle zamane mein koi Mir bhi tha"]),
    urdu("ghalib-andaz-e-bayan", "Mirza Ghalib", &["Hain aur bhi duniya mein sukhanvar bahut achhe", "Kehte hain ke Ghalib ka hai andaz-e-bayan aur"]),
    urdu("ghalib-visal", "Mirza Ghalib", &["Ye na thi hamari qismat ke visal-e-yaar hota", "Agar aur jeete rehte yahi intezar hota"]),
    urdu("ghalib-insaan-hona", "Mirza Ghalib", &["Bas ke dushwar hai har kaam ka aasan hona", "Aadmi ko bhi muyassar nahin insaan hona"]),
    urdu("ghalib-lahu", "Mirza Ghalib", &["Ragon mein daudte phirne ke hum nahin qayal", "Jab aankh hi se na tapka to phir lahu kya hai"]),
    urdu("ghalib-neend", "Mirza Ghalib", &["Koi ummeed bar nahin aati", "Koi soorat nazar nahin aati", "Maut ka ek din mu'ayyan hai", "Neend kyun raat bhar nahin aati"]),
    urdu("ghalib-na-hota", "Mirza Ghalib", &["Na tha kuchh to Khuda tha, kuchh na hota to Khuda hota", "Duboya mujh ko hone ne, na hota main to kya hota"]),
    urdu("ghalib-raunaq", "Mirza Ghalib", &["Un ke dekhe se jo aa jaati hai munh par raunaq", "Wo samajhte hain ke beemar ka haal achha hai"]),
    urdu("ghalib-dard", "Mirza Ghalib", &["Dard minnat-kash-e-dawa na hua", "Main na achha hua bura na hua"]),
    urdu("mir-patta-patta", "Mir Taqi Mir", &["Patta patta boota boota haal hamara jaane hai", "Jaane na jaane gul hi na jaane baagh to saara jaane hai"]),
    urdu("mir-nazuki", "Mir Taqi Mir", &["Nazuki us ke lab ki kya kahiye", "Pankhudi ik gulab ki si hai"]),
    urdu("mir-ibtida", "Mir Taqi Mir", &["Ibtida-e-ishq hai rota hai kya", "Aage aage dekhiye hota hai kya"]),
    urdu("iqbal-khudi", "Allama Iqbal", &["Khudi ko kar buland itna ke har taqdeer se pehle", "Khuda bande se khud pooche bata teri raza kya hai"]),
    urdu("iqbal-sitaron-se-aage", "Allama Iqbal", &["Sitaron se aage jahan aur bhi hain", "Abhi ishq ke imtihan aur bhi hain"]),
    urdu("iqbal-shaheen", "Allama Iqbal", &["Tu shaheen hai parwaz hai kaam tera", "Tere saamne aasman aur bhi hain"]),
    urdu("iqbal-nasheman", "Allama Iqbal", &["Nahin tera nasheman qasr-e-sultani ke gumbad par", "Tu shaheen hai basera kar pahadon ki chatanon mein"]),
    urdu("iqbal-nargis", "Allama Iqbal", &["Hazaron saal nargis apni be-noori pe roti hai", "Badi mushkil se hota hai chaman mein deeda-var paida"]),
    urdu("iqbal-sare-jahan", "Allama Iqbal", &["Saare jahan se achha Hindostan hamara", "Hum bulbulen hain is ki ye gulsitan hamara"]),
    urdu("iqbal-lab-pe-aati", "Allama Iqbal", &["Lab pe aati hai dua ban ke tamanna meri", "Zindagi shama ki soorat ho khudaya meri"]),
    urdu("faiz-aur-bhi-dukh", "Faiz Ahmad Faiz", &["Aur bhi dukh hain zamane mein mohabbat ke siwa", "Rahaten aur bhi hain vasl ki rahat ke siwa"]),
    urdu("faiz-bol", "Faiz Ahmad Faiz", &["Bol ke lab azad hain tere", "Bol zaban ab tak teri hai"]),
    urdu("faiz-gulon-mein", "Faiz Ahmad Faiz", &["Gulon mein rang bhare baad-e-nau-bahar chale", "Chale bhi aao ke gulshan ka karobar chale"]),
    urdu("faiz-sham", "Faiz Ahmad Faiz", &["Dil na-umeed to nahin nakaam hi to hai", "Lambi hai gham ki shaam magar shaam hi to hai"]),
    urdu("faiz-dua", "Faiz Ahmad Faiz", &["Aaiye haath uthayen hum bhi", "Hum jinhen rasm-e-dua yaad nahin"]),
    urdu("faraz-ranjish", "Ahmad Faraz", &["Ranjish hi sahi dil hi dukhane ke liye aa", "Aa phir se mujhe chhod ke jaane ke liye aa"]),
    urdu("faraz-bichhde", "Ahmad Faraz", &["Ab ke hum bichhde to shayad kabhi khwabon mein milen", "Jis tarah sookhe hue phool kitabon mein milen"]),
    urdu("faraz-suna-hai", "Ahmad Faraz", &["Suna hai log use aankh bhar ke dekhte hain", "So us ke shehr mein kuchh din thehar ke dekhte hain"]),
    urdu("jaun-ajeeb", "Jaun Elia", &["Main bhi bahut ajeeb hoon itna ajeeb hoon ke bas", "Khud ko tabah kar liya aur malaal bhi nahin"]),
    urdu("jaun-ghar", "Jaun Elia", &["Kaun is ghar ki dekh-bhaal kare", "Roz ik cheez toot jaati hai"]),
    urdu("jaun-khatra", "Jaun Elia", &["Ab nahin koi baat khatre ki", "Ab sabhi ko sabhi se khatra hai"]),
    urdu("jaun-bhaate", "Jaun Elia", &["Kitne aish se rehte honge kitne itraate honge", "Jaane kaise log wo honge jo us ko bhaate honge"]),
    urdu("parveen-ruswai", "Parveen Shakir", &["Kaise keh doon ke mujhe chhod diya hai us ne", "Baat to sach hai magar baat hai ruswai ki"]),
    urdu("parveen-harjai", "Parveen Shakir", &["Wo kahin bhi gaya lauta to mere paas aaya", "Bas yahi baat hai achhi mere harjai ki"]),
    urdu("badr-ujale", "Bashir Badr", &["Ujale apni yaadon ke hamare saath rehne do", "Na jaane kis gali mein zindagi ki shaam ho jaaye"]),
    urdu("badr-dushmani", "Bashir Badr", &["Dushmani jam kar karo lekin ye gunjaish rahe", "Jab kabhi hum dost ho jaayen to sharminda na hon"]),
    urdu("badr-faasle", "Bashir Badr", &["Koi haath bhi na milayega jo gale miloge tapak se", "Ye naye mizaj ka shehr hai zara faasle se mila karo"]),
    urdu("badr-bastiyan", "Bashir Badr", &["Log toot jaate hain ek ghar banane mein", "Tum taras nahin khaate bastiyan jalane mein"]),
    urdu("nida-mukammal", "Nida Fazli", &["Kabhi kisi ko mukammal jahan nahin milta", "Kahin zameen kahin aasman nahin milta"]),
    urdu("nida-masjid", "Nida Fazli", &["Ghar se masjid hai bahut door chalo yun kar len", "Kisi rote hue bachche ko hansaya jaaye"]),
    urdu("nida-aadmi", "Nida Fazli", &["Har aadmi mein hote hain das bees aadmi", "Jis ko bhi dekhna ho kai baar dekhna"]),
    urdu("rahat-mitti", "Rahat Indori", &["Sabhi ka khoon hai shamil yahan ki mitti mein", "Kisi ke baap ka Hindostan thodi hai"]),
    urdu("rahat-dhuan", "Rahat Indori", &["Agar khilaf hain hone do jaan thodi hai", "Ye sab dhuan hai koi aasman thodi hai"]),
    urdu("firaq-yaad", "Firaq Gorakhpuri", &["Ek muddat se teri yaad bhi aayi na hamen", "Aur hum bhool gaye hon tujhe aisa bhi nahin"]),
    urdu("majrooh-karvan", "Majrooh Sultanpuri", &["Main akela hi chala tha jaanib-e-manzil magar", "Log saath aate gaye aur karvan banta gaya"]),
    urdu("sahir-afsana", "Sahir Ludhianvi", &["Wo afsana jise anjam tak lana na ho mumkin", "Use ek khoobsurat mod de kar chhodna achha"]),
    urdu("momin-goya", "Momin Khan Momin", &["Tum mere paas hote ho goya", "Jab koi doosra nahin hota"]),
    urdu("akbar-badnaam", "Akbar Allahabadi", &["Hum aah bhi karte hain to ho jaate hain badnaam", "Wo qatl bhi karte hain to charcha nahin hota"]),
    urdu("zauq-kidhar", "Sheikh Ibrahim Zauq", &["Ab to ghabra ke ye kehte hain ke mar jaayenge", "Mar ke bhi chain na paaya to kidhar jaayenge"]),
    urdu("wasim-saleeqe", "Waseem Barelvi", &["Wo jhooth bol raha tha bade saleeqe se", "Main aitbaar na karta to aur kya karta"]),
    urdu("munir-der", "Munir Niazi", &["Hamesha der kar deta hoon main har kaam karne mein", "Zaroori baat kehni ho koi wada nibhana ho"]),
    urdu("jalib-dastoor", "Habib Jalib", &["Aise dastoor ko subh-e-be-noor ko", "Main nahin manta main nahin jaanta"]),
    urdu("gulzar-shaakh", "Gulzar", &["Haath chhoote bhi to rishte nahin chhoda karte", "Waqt ki shaakh se lamhe nahin toda karte"]),
    urdu("qasmi-samundar", "Ahmad Nadeem Qasmi", &["Kaun kehta hai ke maut aayi to mar jaaunga", "Main to dariya hoon samundar mein utar jaaunga"]),
    english("dickinson-hope", "Emily Dickinson", &["\"Hope\" is the thing with feathers -", "That perches in the soul -", "And sings the tune without the words -", "And never stops - at all -"]),
    english("frost-gold", "Robert Frost", &["Nature's first green is gold,", "Her hardest hue to hold.", "Her early leaf's a flower;", "But only so an hour.", "Then leaf subsides to leaf.", "So Eden sank to grief,", "So dawn goes down to day.", "Nothing gold can stay."]),
    english("frost-fire-ice", "Robert Frost", &["Some say the world will end in fire,", "Some say in ice.", "From what I've tasted of desire", "I hold with those who favor fire."]),
    english("frost-road", "Robert Frost", &["Two roads diverged in a wood, and I—", "I took the one less traveled by,", "And that has made all the difference."]),
    english("blake-grain", "William Blake", &["To see a World in a Grain of Sand", "And a Heaven in a Wild Flower,", "Hold Infinity in the palm of your hand", "And Eternity in an hour."]),
    english("tagore-without-fear", "Rabindranath Tagore", &["Where the mind is without fear and the head is held high;", "Where knowledge is free;", "Where the world has not been broken up into fragments", "By narrow domestic walls;"]),
    english("shakespeare-18", "William Shakespeare", &["Shall I compare thee to a summer's day?", "Thou art more lovely and more temperate."]),
    english("keats-beauty", "John Keats", &["A thing of beauty is a joy for ever:", "Its loveliness increases; it will never", "Pass into nothingness;"]),
    english("yeats-dreams", "W. B. Yeats", &["But I, being poor, have only my dreams;", "I have spread my dreams under your feet;", "Tread softly because you tread on my dreams."]),
    english("henley-invictus", "William Ernest Henley", &["It matters not how strait the gate,", "How charged with punishments the scroll,", "I am the master of my fate,", "I am the captain of my soul."]),
    english("gibran-children", "Kahlil Gibran", &["Your children are not your children.", "They are the sons and daughters of Life's longing for itself.", "They come through you but not from you,", "And though they are with you yet they belong not to you."]),
    english("tennyson-ulysses", "Alfred, Lord Tennyson", &["Tho' much is taken, much abides; and tho'", "We are not now that strength which in old days", "Moved earth and heaven, that which we are, we are;", "One equal temper of heroic hearts,", "Made weak by time and fate, but strong in will", "To strive, to seek, to find, and not to yield."]),
    english("wordsworth-daffodils", "William Wordsworth", &["I wandered lonely as a cloud", "That floats on high o'er vales and hills,", "When all at once I saw a crowd,", "A host, of golden daffodils;"]),
    english("fitzgerald-moving-finger", "Omar Khayyam, translated by Edward FitzGerald", &["The Moving Finger writes; and, having writ,", "Moves on: nor all your Piety nor Wit", "Shall lure it back to cancel half a Line,", "Nor all your Tears wash out a Word of it."]),
];

/// A motivational line and who said it, with where when it is known.
pub struct Quote {
    pub id: &'static str,
    pub text: &'static str,
    pub who: &'static str,
}

const fn quote(id: &'static str, text: &'static str, who: &'static str) -> Quote {
    Quote { id, text, who }
}

pub const QUOTES: &[Quote] = &[
    quote("ali-training", "I hated every minute of training, but I said, \"Don't quit. Suffer now and live the rest of your life as a champion.\"", "Muhammad Ali"),
    quote("ali-float", "Float like a butterfly, sting like a bee.", "Muhammad Ali"),
    quote("durant-habit", "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Will Durant, summing up Aristotle in The Story of Philosophy"),
    quote("aurelius-way", "The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius, Meditations"),
    quote("laozi-step", "The journey of a thousand miles begins with a single step.", "Laozi, Tao Te Ching"),
    quote("jordan-failed", "I've missed more than 9,000 shots in my career. I've lost almost 300 games. 26 times I've been trusted to take the game-winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "Michael Jordan"),
    quote("tendulkar-stones", "People throw stones at you and you convert them into milestones.", "Sachin Tendulkar"),
    quote("lee-water", "Empty your mind, be formless, shapeless, like water... Be water, my friend.", "Bruce Lee"),
    quote("kipchoge-limited", "No human is limited.", "Eliud Kipchoge"),
    quote("kipchoge-discipline", "Only the disciplined ones in life are free. If you are undisciplined, you are a slave to your moods and your passions.", "Eliud Kipchoge"),
    quote("gretzky-shots", "You miss 100% of the shots you don't take.", "Wayne Gretzky"),
    quote("roosevelt-arena", "It is not the critic who counts... The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood; who strives valiantly.", "Theodore Roosevelt, \"Citizenship in a Republic\", 1910"),
    quote("gandhi-will", "Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi"),
    quote("vivekananda-arise", "Arise, awake, and stop not till the goal is reached.", "Swami Vivekananda"),
    quote("vivekananda-football", "You will be nearer to Heaven through football than through the study of the Gita.", "Swami Vivekananda"),
    quote("kennedy-fitness", "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", "John F. Kennedy, \"The Soft American\", 1960"),
    quote("rohn-body", "Take care of your body. It's the only place you have to live.", "Jim Rohn"),
    quote("tyson-plan", "Everybody has a plan until they get punched in the mouth.", "Mike Tyson"),
    quote("rocky-hit", "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", "Rocky Balboa (2006), written by Sylvester Stallone"),
    quote("prefontaine-gift", "To give anything less than your best is to sacrifice the gift.", "Steve Prefontaine"),
    quote("goggins-comfortable", "You are in danger of living a life so comfortable and soft that you will die without ever realizing your true potential.", "David Goggins, Can't Hurt Me"),
    quote("nietzsche-stronger", "What does not kill me makes me stronger.", "Friedrich Nietzsche, Twilight of the Idols"),
    quote("seneca-dare", "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", "Seneca, Letters to Lucilius"),
    quote("epictetus-master", "No man is free who is not master of himself.", "Epictetus"),
    quote("lalanne-kingdom", "Exercise is king. Nutrition is queen. Put them together and you've got a kingdom.", "Jack LaLanne"),
    quote("pilates-happiness", "Physical fitness is the first requisite of happiness.", "Joseph Pilates, Return to Life Through Contrology"),
    quote("murakami-pain", "Pain is inevitable. Suffering is optional.", "Haruki Murakami, What I Talk About When I Talk About Running (quoting a runner's mantra)"),
    quote("lombardi-quit", "Winners never quit and quitters never win.", "Vince Lombardi"),
    quote("aurelius-morning", "At dawn, when you have trouble getting out of bed, tell yourself: \"I have to go to work - as a human being.\"", "Marcus Aurelius, Meditations"),
    quote("seneca-suffer", "We suffer more often in imagination than in reality.", "Seneca, Letters to Lucilius"),
    quote("edison-perspiration", "Genius is one percent inspiration, ninety-nine percent perspiration.", "Thomas Edison"),
    quote("beckett-fail-better", "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett, Worstward Ho"),
    quote("einstein-bicycle", "Life is like riding a bicycle. To keep your balance you must keep moving.", "Albert Einstein, in a letter to his son Eduard, 1930"),
    quote("coubertin-struggle", "The important thing in life is not the triumph but the struggle.", "Pierre de Coubertin, founder of the modern Olympics"),
];
